### ISSUE TITLE
Password reset page - styling issue

### ISSUE THREAD

**Issue by JamesPickstone** [TheRestartProject/Fixometer#195] opened 2018-03-02 13:18 UTC
When following a password reset link from an email, the password reset page displays strangely (see screenshot).

Mac OS 10.13.3, Firefox 59.0b13 and Safari 11.0.3 (same issue on both)

![password reset page - firefox](https://user-images.githubusercontent.com/36991534/36900643-012b3958-1e1c-11e8-9f9a-6f3b5f2c77ae.png)

**Comment by ngm** [comment] 2018-03-05 16:50
Confirmed, looks like a closing tag on the password input field got removed during the internationalisation process.

**Comment by ngm** [comment] 2018-03-05 16:54
Fixed by 979d809, pushed to production.  Thanks @JamesPickstone !

**Closed** 2018-03-05 16:54 UTC
Labels: bug, design

**Comment by ngm** [comment] 2018-03-12 12:04
![](https://github.trello.services/images/mini-trello-icon.png) [Bugfix release](https://trello.com/c/rwmmfnCg/12-bugfix-release)
