### ISSUE TITLE
Unable to delete event

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/Fixometer#83] opened 2017-01-25 13:22 UTC
When clicking the delete button for the 'Test location - primrose' event in the list of events in Upcoming Restart Parties, the event isn't deleted.

The event is ID #279, part of the 'Restart paid events' group.

Have recreated this logged in as an administrator.

**Comment by IronRunes** [comment] 2017-03-21 16:04
@ngm is this error specific to this party, or has it happened in other instances as well?

**Comment by ngm** [comment] 2017-03-21 16:12
@IronRunes  I'm pretty sure it's specific to this event - from conversation with @ugomatic , I believe this event had its Wordpress page unpublished or deleted, which would seem the most likely cause of this error?

**Comment by IronRunes** [comment] 2017-03-24 15:45
Ok @ngm , I got it. The problem is that the event has devices connected to it, so MySQL is locking it from being deleted with a key constraint. This is actually a desired feature.  
Problem is that the event, after being loaded with devices, has been back-dated to be able to delete it, thus generating the confusion. 
so this can be fixed by placing the event back in time, deleting the events, setting the event **_BACK TO THE FUTURE_** (omg I actually have been able to say that in context!) and then deleting it.

**Comment by ugomatic** [comment] 2017-03-24 18:27
That makes sense, @IronRunes - all sorted now, thanks

**Closed** 2017-03-24 18:42 UTC
Labels: bug
